export default function PrivacyPolicy() {
  return (
    <main style={{ maxWidth: 700, margin: '40px auto', padding: 24, background: '#fff', color: '#222', borderRadius: 12, boxShadow: '0 2px 12px rgba(0,0,0,0.06)' }}>
      <h1>LLAMAINDEX PRIVACY NOTICE</h1>
<p>Last Updated: 2024-03-30</p>
<p>Welcome to LlamaIndex—a data framework for building large language model applications. This Privacy Notice explains how LlamaIndex Inc. (“LlamaIndex,” “we,” “our,” or “us”) collects, uses, discloses, and otherwise processes personal data.</p>
<p>This Privacy Notice does not address our privacy practices relating to LlamaIndex job applicants, employees and other employment-related individuals, nor data that is not subject to applicable data protection laws (such as deidentified or publicly available information). This Privacy Notice is also not a contract and does not create any legal rights or obligations not otherwise provided by law.</p>
<h1>Our Role in Processing Personal Data</h1>
<p>Data protection laws sometimes differentiate between “controllers” and “processors” of personal data. A “controller” determines the purposes and means (the why and how) of processing personal data. A “processor,” which is sometimes referred to as a “service provider,” processes personal data on behalf of a controller subject to the controller’s instructions.</p>
<p>This Privacy Notice describes our privacy practices where we are acting as the controller of personal data. However, this Privacy Notice does not cover or address how our customers may process personal data when they use our services, or how we may process personal data on their behalf in accordance with their instructions where we are acting as their processor. As a result, we recommend referring to the privacy notice of the customer with which you have a relationship for information on how they engage processors, like us, to process personal data on their behalf. In addition, we are generally not permitted to respond to individual requests relating to personal data we process on behalf of our customers, so we recommend directing any requests to the relevant customer.</p>
<h1>Our Collection and Use of Personal Data</h1>
<p>The categories of personal data we collect depend on how you interact with us and our services. For example, you may provide us your personal data directly when you provide us your contact information, use our services, register for an account, complete an online transaction, participate in an event, contest, sweepstakes, or survey, or otherwise contact us or interact with us through our services.</p>
<p>We also collect personal data automatically when you interact with our websites and other services and may also collect personal data from other sources and third parties.</p>
<h1>Personal Data Provided by Individuals</h1>
<p>We collect the following categories of personal data individuals provide us:</p>
<ul>
<li>Contact Information, including first and last name, phone number, email address, mailing address, and communication preferences. We use this information primarily to fulfill your request or transaction, to communicate with you directly, and to send you marketing communications in accordance with your preferences.</li>
<li>Professional Information, including job title, company name, professional background, and the nature of your relationship with us. We use this information primarily to fulfill your request or transaction, to determine how we communicate with you, to administer your account, to provide you with our services, and for customer support purposes.</li>
<li>Account Information, including first and last name, email address, phone number, account credentials or one-time passcodes, transaction history, and the history of the use of our services. We use this information primarily to administer your account, provide you with our services, communicate with you regarding your account and your use of our services, and for customer support purposes.</li>
</ul>
<hr/>
<h1>Privacy Notice</h1>
<h1>Customer Content</h1>
<p>Customer Content, including any files, documents, audio, videos, images, data, or communications you choose to input, upload, or transmit to our services. We use this content primarily to provide you with our services, to facilitate your requests, and to improve our services.</p>
<h1>Payment Information</h1>
<p>Payment Information, including payment card information, billing address, and other financial information such as routing and account number. Please note that we use third-party payment processors, including Stripe, to process payments made to us. We do not retain any personally identifiable financial information, such as payment card number, you provide these third-party payment providers in connection with payments. Rather, all such information is provided directly by you to our third-party payment processors. The payment processor’s use of your personal data is governed by their privacy notice. To view Stripe’s privacy policy, please click here.</p>
<h1>Event, Contest, Sweepstakes, and Survey Information</h1>
<p>Event, Contest, Sweepstakes, and Survey Information, including information provided when you sign up for an event, enter a contest or promotion, complete a survey, or submit a testimonial. We use this information primarily to administer and facilitate our services, respond to your submission, communicate with you, conduct market research, inform our marketing and advertising activities, improve and grow our business, and facilitate the related event, content, sweepstakes, or survey.</p>
<h1>Feedback and Support Information</h1>
<p>Feedback and Support Information, including the contents of custom messages sent through the forms, chat platforms, email addresses, or other contact information we make available to customers, as well as recordings of calls with us, where permitted by law (including through the use of automated tools provided by us or our third-party providers). We use this information primarily to investigate and respond to your inquiries, to communicate with you, and to improve our services.</p>
<p>If you choose to contact us, we may need additional information to fulfill the request or respond to your inquiry. We may provide additional privacy disclosures where the scope of the request we receive or personal data we require fall outside the scope of this Privacy Notice. In that case, the additional privacy disclosures will govern how we may process the information you provide at that time.</p>
<h1>Personal Data Automatically Collected</h1>
<p>We, and our third-party partners, automatically collect information you provide to us and information about how you access and use our services when you engage with us. We typically collect this information through the use of a variety of our own and our third-party partners’ automatic data collection technologies, including (i) cookies or small data files that are stored on an individual’s computer and (ii) other, related technologies, such as web beacons, pixels, embedded scripts, SDKs, location-identifying technologies and logging technologies. Information we collect automatically about you may be combined with other personal data we collect directly from you or receive from other sources.</p>
<p>We, and our third-party partners, use automatic data collection technologies to automatically collect the following data when you use our services or otherwise engage with us:</p>
<h1>Information About Your Device and Network</h1>
<p>Information About Your Device and Network, including the device type, manufacturer, and model, operating system, IP address, browser type, Internet service provider, and unique identifiers associated with you, your device, or your network (including, for example, a persistent device identifier or advertising ID). We employ third-party technologies designed to allow us to recognize when two or more devices are likely being used by the same individual and may leverage these technologies (where permitted) to link information collected from different devices.</p>
<h1>Information About the Way Individuals Use Our Services and Interact With Us</h1>
<p>Information About the Way Individuals Use Our Services and Interact With Us, including the site from which you came, the site to which you are going when you leave our services, how frequently you access our services, whether you open emails or click the links contained in emails, whether you access our services from multiple devices, and other browsing behavior and actions you take on our services (such as the pages you visit, the content you view, the queries you make on our services, the communications you have through our services, and the content, links and ads you interact with). We employ third-party technologies designed to allow us to collect detailed information about browsing behavior and actions that you take on our services, which may record your mouse movements, scrolling, clicks, and keystroke activity on our services and other browsing, search or purchasing behavior. These third-party technologies may also record information you enter when you interact with our services or engage in chat features or other communication platforms we provide.</p>
<h1>Information About Your Location</h1>
<p>Information About Your Location, including general geographic location that we or our third-party providers may derive from your IP address.</p>
<h2>All of the information collected automatically through these tools allows us to improve your customer experience. For example, we may use this information to enhance and personalize your user experience, to monitor and improve our services, and to improve the effectiveness of our services, offers, advertising, communications and customer service.</h2>
<p>may also use this information to: (a) remember information so that you will not have to re-enter it during your visit or the next time you visit our services; (b) provide custom, personalized content and information, including targeted content and advertising; (c) identify you across multiple devices; (d) provide and monitor the effectiveness of our services; (e) monitor aggregate metrics such as total number of visitors, traffic, usage, and demographic patterns on our website; (f) diagnose or fix technology problems; and (g) otherwise to plan for and enhance our services.</p>
<p>For information about the choices you may have in relation to our use of automatic data collection technologies, please refer to the Your Privacy Choices section below.</p>
<h1>Personal Data from Other Sources and Third Parties</h1>
<p>We may receive the same categories of personal data as described above from the following sources and other parties:</p>
<ul>
<li>Single Sign-On: We may provide you the ability to log in to our services through certain third-party accounts you maintain. When you use these single sign-on protocols to access our services, we do not receive your login credentials for the relevant third-party service. Instead, we receive tokens from the single sign-on protocol to help identify you in our system (such as by your username) and confirm you successfully authenticated through the single sign-on protocol. This information allows us to more easily provide you access to our services.</li>
<li>Employers: If you interact with our services in connection with your employment, we may obtain personal data about you from your employer or another company for which you work. For example, we may obtain your contact information from your employer to allow us to communicate with you about your employer’s customer relationship with us.</li>
<li>Other Customers: We may receive your personal data from our other customers. For example, a customer may provide us with your contact information as a part of a referral.</li>
<li>Social Media: When you interact with our services through other social media networks, such as when you follow us or share our content on other social networks, we may receive some information that you permit the social network to share with third parties. The data we receive is dependent upon your privacy settings with the social network, and may include profile information, profile picture, username, and any other information you permit the social network to share with third parties. You should always review and, if necessary, adjust your privacy settings on third-party websites and social media networks and services before sharing information and/or linking or connecting them to other services. We use this information primarily to operate, maintain, and provide to you the features and functionality of our services, as well as to communicate directly with you, such as to send you messages about features that may be of interest to you.</li>
<li>Advertisers, Influencers, and Publishers: We engage in advertising both on our services and through third-party services. Advertisers, influencers, and publishers may share personal data with us in connection with our advertising efforts. For example, we may obtain information about whether an advertisement on our services led to a successful engagement between you and a third-party advertiser.</li>
<li>Business Partners: We may receive your information from our business partners, such as companies that offer their products and/or services as a part of or in connection with our services. For example, certain of our services allow our customers to integrate third-party services. If you choose to leverage these third-party service integrations, we may receive confirmation from our business partner regarding whether you are an existing customer of their services.</li>
<li>Service Providers: Our service providers that perform services on our behalf, such as analytics and certain marketing providers, collect personal data and often share some or all of this information with us. For example, we receive personal data you may submit in response to requests for feedback to our survey providers.</li>
<li>Other Sources: We may also collect personal data about you from other sources, including publicly available sources, third-party data providers, brand partnerships, or through transactions such as mergers and acquisitions.</li>
</ul>
<hr/>
<h1>Inferences</h1>
<p>We may generate inferences or predictions about you and your interests and preferences based on the other personal data we collect and the interactions we have with you.</p>
<h1>Additional Uses of Personal Data</h1>
<p>In addition to the primary purposes for using personal data described above, we may also use personal data we collect to:</p>
<ul>
<li>Fulfill or meet the reason the information was provided, such as to fulfill our contractual obligations, to facilitate payment for our services, or to deliver the services requested;</li>
<li>Manage our organization and its day-to-day operations;</li>
<li>Communicate with you, including via email, text message, chat, social media and/or telephone calls;</li>
<li>Facilitate the relationship we have with you and, where applicable, the company you represent;</li>
<li>Request you provide us feedback about our service offerings;</li>
<li>Address inquiries or complaints made by or about an individual in connection with our services;</li>
<li>Create and maintain accounts for our users;</li>
<li>Verify your identity and entitlement to our services;</li>
<li>Register you for and provide you access to events, contests, sweepstakes, and surveys;</li>
<li>Market our services to you, including through email, phone, text message, and social media;</li>
<li>Administer, improve, and personalize our services, including by recognizing you and remembering your information when you return to our services;</li>
<li>Develop, operate, improve, maintain, protect, and provide the features and functionality of our services;</li>
<li>Identify and analyze how you use our services;</li>
<li>Infer additional information about you from your use of our services, such as your interests;</li>
<li>Create aggregated or de-identified information that cannot reasonably be used to identify you, which information we may use for purposes outside the scope of this Privacy Notice;</li>
<li>Conduct research and analytics on our user base and our services, including to better understand the demographics of our users;</li>
<li>Improve and customize our services to address the needs and interests of our user base and other individuals we interact with;</li>
<li>Test, enhance, update, and monitor the services, or diagnose or fix technology problems;</li>
<li>Help maintain and enhance the safety, security, and integrity of our property, services, technology, assets, and business;</li>
<li>Defend, protect, or enforce our rights or applicable contracts and agreements (including our Terms of Use), as well as to resolve disputes, to carry out our obligations and enforce our rights, and to protect our business interests and the interests and rights of third parties;</li>
<li>Detect, prevent, investigate, or provide notice of security incidents or other malicious, deceptive, fraudulent, or illegal activity and protect the rights and property of LlamaIndex and others;</li>
<li>Facilitate business transactions and reorganizations impacting the structure of our business;</li>
<li>Comply with contractual and legal obligations and requirements; and</li>
<li>Fulfill any other purpose for which you provide your personal data, or for which you have otherwise consented.</li>
</ul>
<h1>Our Disclosure of Personal Data</h1>
<h2>We disclose or otherwise make available personal data in the following ways:</h2>
<p>− To Your Employer: If you interact with our services in connection with your employment, we may disclose personal data to your employer or another company for which you work. For example, we may provide information to your employer about your usage of our services in connection with your work for them.</p>
<p>− To Marketing Providers: We coordinate and share personal data with our marketing providers in order to advertise and communicate with you about the services we make available.</p>
<p>− To Ad Networks and Advertising Partners: We work with third-party ad networks and advertising partners to deliver advertising and personalized content on our services, on other websites and services, and across other devices. These parties may collect information automatically from your browser or device when you visit our websites and other services through the use of cookies and related technologies. This information is used to provide and inform targeted advertising, as well as to provide advertising-related services such as reporting, attribution, analytics, and market research.</p>
<p>− To Business Partners: We may share personal data with our business partners, or we may allow our business partners to collect personal data directly from you in connection with our services. Our business partners may use your personal data for their own business and commercial purposes, including to send you information about their services.</p>
<p>− To Service Providers: We engage other third parties to perform certain services on our behalf in connection with the uses of personal data described in the sections above. Depending on the applicable services, these service providers may process personal data on our behalf or have access to personal data while performing services on our behalf.</p>
<p>− To Other Businesses as Needed to Provide Services: We may share personal data with third parties you engage with through our services or as needed to fulfill a request or transaction including, for example, payment processing services.</p>
<p>− In Connection with a Business Transaction or Reorganization: We may take part in or be involved with a business transaction or reorganization, such as a merger, acquisition, joint venture, or financing or sale of company assets. We may disclose, transfer, or assign personal data to a third party during negotiation of, in connection with, or as an asset in such a business transaction or reorganization. Also, in the unlikely event of our bankruptcy, receivership, or insolvency, your personal data may be disclosed, transferred, or assigned to third parties in connection with the proceedings or disposition of our assets.</p>
<p>− To Comply with Legal Obligations and Rights: We may disclose personal data to third parties, such as legal advisors and law enforcement:</p>
<ul>
<li>in connection with the establishment, exercise, or defense of legal claims;</li>
<li>to comply with laws or to respond to lawful requests and legal process;</li>
<li>to protect our rights and property and the rights and property of our agents, customers, and others, including to enforce our agreements, policies, and terms of use;</li>
<li>to detect, suppress, or prevent fraud;</li>
<li>to reduce credit risk and collect debts owed to us;</li>
<li>to protect the health and safety of us, our customers, or any person; or</li>
<li>as otherwise required by applicable law.</li>
</ul>
<p>− With Your Consent or Direction: We may disclose your personal data to certain other third parties or publicly with your consent or direction. For example, with your permission, we may post your testimonial on our websites.</p>
<h1>Your Privacy Choices</h1>
<h2>The following privacy choices are made available to all individuals with whom we interact. You may also have additional choices regarding your personal data depending on your location or residency.</h2>
<h1>Communication Preferences</h1>
<p>Email Communication Preferences: You can stop receiving promotional email communications from us by clicking on the “unsubscribe” link provided in any of our email communications. Please note you cannot opt-out of service-related email communications (such as, account verification, transaction confirmation, or service update emails).</p>
<h1>Automatic Data Collection Preferences</h1>
<p>You may be able to utilize third-party tools and features to restrict our use of automatic data collection technologies. For example, (i) most browsers allow you to change browser settings to limit automatic data collection technologies on websites, (ii) most email providers allow you to prevent the automatic downloading of images in emails that may contain automatic data collection technologies, and (iii) many devices allow you to change your device settings to limit automatic data collection technologies for device applications. Please note that blocking automatic data collection technologies through third-party tools and features may negatively impact your experience using our services, as some features and offerings may not work properly or at all. Depending on the third-party tool or feature you use, you may not be able to block all automatic data collection technologies, or you may need to update your preferences on multiple devices or browsers. We do not have any control over these third-party tools and features and are not responsible if they do not function as intended.</p>
<h1>Targeted Advertising Preferences</h1>
<p>We engage third parties to help us facilitate targeted advertising designed to show you personalized ads based on predictions of your preferences and interests developed using personal data we maintain and personal data our third-party partners obtain from your activity over time and across nonaffiliated websites and other services. The data we and our third-party partners use for purposes of facilitating targeted advertising, as well as to provide advertising-related services such as reporting, attribution, analytics, and market research, are primarily collected through the use of a variety of automatic data collection technologies, including cookies, web beacons, pixels, embedded scripts, mobile SDKs, location-identifying technologies and logging technologies. We may share a common account identifier (such as a hashed email address or user ID) with our third-party advertising partners to help link the personal data we and our third-party partners collect to the same person, or otherwise target advertising to an individual on a third-party website or platform.</p>
<p>In addition to taking the steps set forth in the Automatic Data Collection Preferences section above, you may be able to further exercise control over the advertisements that you see by leveraging one or more targeted advertising opt-out programs. For example:</p>
<ul>
<li>Device-Specific Opt-Out Programs: Certain devices provide individuals the option to turn off targeted advertising for the entire device (such as Apple devices through their App Tracking Transparency framework or Android devices through their opt out of ads personalization feature). Please refer to your device manufacturer’s user guides for additional information about implementing any available device-specific targeted advertising opt-outs.</li>
<li>Digital Advertising Alliance: The Digital Advertising Alliance allows individuals to opt out of receiving online interest-based targeted advertisements from companies that participate in their program. Please follow the instructions at https://optout.aboutads.info/?c=2&amp;lang=EN for browser-based advertising and https://www.youradchoices.com/appchoices for app-based advertising to opt out of targeted advertising carried out by our third-party partners and other third parties that participate in the Digital Advertising Alliance’s self-regulatory program.</li>
<li>Network Advertising Initiative: The Network Advertising Initiative similarly allows individuals to opt out of receiving online interest-based targeted advertisements from companies that participate in their program. Please follow the instructions at https://optout.networkadvertising.org/?c=1 to opt out of browser-based targeted advertising carried out by our third-party partners and other third parties that participate in the Network Advertising Initiative’s self-regulatory program.</li>
<li>Platform-Specific Opt-Out Programs: Certain third-party platforms provide individuals the option to turn off targeted advertising for the entire platform (such as certain social media platforms). Please refer to your platform provider’s user guides for additional information about implementing any available platform-specific targeted advertising opt-outs.</li>
</ul>
<h2>Please note that when you opt out of receiving interest-based advertisements through one of these programs, this does not mean you will no longer see advertisements from us or on our services. Instead, it means that the online ads you do...</h2>
<h1>Partner-Specific Preferences</h1>
<p>Certain of our third-party providers and partners offer additional ways that you may exercise control over your personal data, or automatically impose limitations on the way we can use personal data in connection with the services they provide:</p>
<ul>
<li>Device-Specific / Platform-Specific Preferences: The device and/or platform you use to interact with us (such as your mobile device or social media provider), may provide you additional choices regarding the data you choose to share with us. For example, many mobile devices allow you to change your device permissions to prevent our services from accessing certain types of information from your device (such as your contact lists), and many social media platforms allow you to change your platform permissions to prevent integrated products and services from accessing certain types of information connected with your profile. Please refer to your device or platform provider’s user guides for additional information about implementing any available platform-specific targeted advertising opt-outs.</li>
<li>Google Analytics: Google Analytics allows us to better understand how our customers interact with our services. For information on how Google Analytics collects and processes data, as well as how you can control information sent to Google, review Google&#x27;s website here: www.google.com/policies/privacy/partners/. You can learn about Google Analytics’ currently available opt-outs, including the Google Analytics Browser Add-On here: https://tools.google.com/dlpage/gaoptout/. We may also utilize certain forms of display advertising and other advanced features through Google Analytics. These features enable us to use first-party cookies (such as the Google Analytics cookie) and third-party cookies (such as the DoubleClick advertising cookie) or other third-party cookies together to inform, optimize, and display ads based on your past visits to our services. You may control your advertising preferences or opt-out of certain Google advertising products by visiting Google’s My Ad Center, currently available at https://myadcenter.google.com/?ref=help-center.</li>
</ul>
<h1>Children’s Personal Data</h1>
<p>Our services are not directed to, and we do not intend to, or knowingly, collect or solicit personal data from children under the age of 18. If an individual is under the age of 18, they should not use our services or otherwise provide us with any personal data either directly or by other means. If a child under the age of 18 has provided personal data to us, we encourage the child’s parent or guardian to contact us to request that we remove the personal data from our systems. If we learn that any personal data we collect has been provided by a child under the age of 18, we will promptly delete that personal data.</p>
<h1>Investor Personal Data</h1>
<p>In addition to the personal data practices outlined above, we also collect personal data from shareholders and investors of our company, including share purchasing history, number of shares held, value of the shares, and the holder of record’s name and address. We use this information primarily to manage investor relations and investments in our company, including by providing you information about our company and related investments, processing investment transactions, preparing tax returns and other investor-related documents, and managing our cap table. We may also use this information for the purposes set forth in the Additional Uses of Personal Data section above and disclose this information to third parties in furtherance of these purposes as set forth in the Our Disclosure of Personal Data section above, as permitted by law.</p>
<h1>Retention of Personal Data</h1>
<h2>We will usually retain the personal data we collect about you for no longer than reasonably necessary to fulfil the purposes for which it was collected, and in accordance with our legitimate business interests and applicable law. However, if necessary, we may retain personal data for longer periods of time as required under applicable law or as needed to resolve disputes or protect our legal rights.</h2>
<p>To determine the appropriate duration of the retention of personal data, we consider the amount, nature, and sensitivity of the personal data, the potential risk of harm from unauthorized use or disclosure of personal data and if we can attain our objectives by other means, as well as our legal, regulatory, tax, accounting, and other applicable obligations.</p>
<p>Once retention of the personal data is no longer reasonably necessary for the purposes outlined above, we will either delete or deidentify the personal data or, if that is not possible (for example, because personal data has been stored in backup archives), we will securely store the personal data and isolate it from further active processing until deletion or deidentification is possible.</p>
<h1>Third-Party Websites and Services</h1>
<p>Our services may include links to third-party websites, plug-ins, applications, and other services. Except where we post, link to, or expressly adopt or refer to this Privacy Notice, this Privacy Notice does not apply to any personal data practices of third parties. To learn about the personal data practices of third parties, please visit their respective privacy notices.</p>
<h1>Updates to This Privacy Notice</h1>
<p>We may update this Privacy Notice from time to time. When we make changes to this Privacy Notice, we will change the date at the beginning of this Privacy Notice. If we make material changes to this Privacy Notice, we will notify individuals by email to their registered email address, by prominent posting on this website or our other platforms, or through other appropriate communication channels. All changes shall be effective from the date of publication unless otherwise provided.</p>
<h1>Contact Us</h1>
<p>If you have any questions or requests in connection with this Privacy Notice or other privacy-related matters, please send an email to privacy@runllama.ai.</p>
    </main>
  );
} 
