export default function TermsOfService() {
  return (
    <main style={{ maxWidth: 700, margin: '40px auto', padding: 24, background: '#fff', color: '#222', borderRadius: 12, boxShadow: '0 2px 12px rgba(0,0,0,0.06)' }}>
      <h1>Terms of Service</h1>
<p>Last Modified: [2024-06-07]</p>
<p>These Terms of Service (these “Terms”) describe the terms and conditions by which you may access and/or use the website(s), including http://llamaindex.ai/, http://cloud.llamaindex.ai/, and any successor URL(s) (the “Sites”), and any and all related software, documentation, and online, mobile-enabled, and/or digital services (collectively, including the Sites and the Apps, the “Service”) provided by LlamaIndex, Inc. (including its successors and assigns, “LlamaIndex” “we,” “our,” or “us”). By accessing and/or using the Service, or by clicking a button or checking a box marked “I Agree” (or something similar), you signify that you have read, understood, and agree to be bound by these Terms, and you acknowledge that you have read and understood our Privacy Notice, as further described in Section 8.1 (Privacy). We reserve the right to modify these Terms, and we will provide notice of material changes as described below. These Terms apply to all visitors and users of the Service, and to all others who access the Service (collectively, “Users,” and, as applicable to you, “you” or “your”).</p>
<p>PLEASE READ THESE TERMS CAREFULLY TO ENSURE THAT YOU UNDERSTAND EACH PROVISION. THESE TERMS CONTAIN A MANDATORY INDIVIDUAL ARBITRATION PROVISION IN SECTION 14.2 (THE “ARBITRATION AGREEMENT”) AND A CLASS ACTION/JURY TRIAL WAIVER PROVISION IN SECTION 14.3 (THE “CLASS ACTION/JURY TRIAL WAIVER”) THAT REQUIRE, UNLESS YOU OPT OUT PURSUANT TO THE INSTRUCTIONS IN THE ARBITRATION AGREEMENT, THE EXCLUSIVE USE OF FINAL AND BINDING ARBITRATION ON AN INDIVIDUAL BASIS TO RESOLVE DISPUTES BETWEEN YOU AND US, INCLUDING ANY CLAIMS THAT AROSE OR WERE ASSERTED BEFORE YOU AGREED TO THESE TERMS. TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW (AS DEFINED BELOW), YOU EXPRESSLY WAIVE YOUR RIGHT TO SEEK RELIEF IN A COURT OF LAW AND TO HAVE A JURY TRIAL ON YOUR CLAIMS, AS WELL AS YOUR RIGHT TO PARTICIPATE AS A PLAINTIFF OR CLASS MEMBER IN ANY CLASS, COLLECTIVE, PRIVATE ATTORNEY GENERAL, OR REPRESENTATIVE ACTION OR PROCEEDING.</p>
<h1>1. How We Administer the Service</h1>
<h1>1.1. Eligibility.</h1>
<h2>This is a contract between you and LlamaIndex. You must read and agree to these Terms before using the Service. If you do not agree, you may not use the Service. You may use the Service only if you can form a legally binding contract with us, and only in compliance with these Terms and all applicable local, state, national, and international laws, rules, and regulations (“Applicable Law”). Without limiting the generality of the foregoing, any access to, or use of, the Service by anyone who is a minor (which is under the age of 18 in most jurisdictions) in any applicable jurisdiction (a “Minor”) is strictly prohibited and in violation of these Terms, unless such access and/or use is supervised by a parent or legal guardian (“Parent”) who: (a) has read and understands these Terms; (b) approves all rights granted, and all obligations undertaken, by the Minor hereunder; and (c) agrees to be bound by these Terms. If you are a Parent of a User who is a Minor, then, by allowing such Minor to access and/or use the Service, you are subject to these Terms and responsible for such Minor’s activity on the Service. With respect to the Parent of a User who is a Minor, “you,” as used in these Terms in the context of a license grant, assignment, restriction, obligation, acknowledgment, representation, warranty, or covenant, or in any similar context, means “the Parent, on behalf of the Parent and the Minor,” and “your” has the corresponding meaning. The Service is not available to any Users we previously removed from the Service.</h2>
<h1>1.2. User Accounts</h1>
<h1>(a) Your User Account.</h1>
<p>Your account on the Service (your “User Account”) gives you access to certain services and functionalities that we may, in our sole discretion, establish and maintain as part of the Service from time to time. You acknowledge that, notwithstanding anything to the contrary herein, you do not own your User Account, nor do you possess any rights to data stored by or on behalf of LlamaIndex on the servers running the Service. We may maintain different types of User Accounts for different types of Users.</p>
<h1>(b) Organizational Accounts.</h1>
<p>An individual may access and/or use the Service on behalf of a company or other entity, such as that individual’s employer (such entity, an “Organization”). In such cases, notwithstanding anything to the contrary herein:</p>
<ol>
<li>these Terms are an agreement between (a) us and such individual and (b) us and that Organization;</li>
<li>“you,” as used in these Terms in the context of a license grant, assignment, restriction, obligation, acknowledgment, representation, warranty, or covenant, or in any similar context, means (a) such individual and (b) “the Organization, on behalf of the Organization and its subsidiaries and affiliates, and its and their respective directors, officers, employees, contractors, agents, and other representatives who access and/or use the Service (collectively, “Org Users”)”; and “your” has the corresponding meanings;</li>
<li>such individual represents and warrants to having the authority to bind that Organization to these Terms (and, in the absence of such authority, such individual may not access, nor use, the Service);</li>
<li>such individual’s acceptance of these Terms will bind that Organization to these Terms;</li>
<li>we may disclose information regarding such individual and such individual’s access to and use of the Service to that Organization;</li>
<li>such individual’s right to access and use the Service may be suspended or terminated (and the administration of the applicable User Account may be transferred) if such individual ceases to be associated with, or ceases to use an email address associated with or provisioned by, that Organization;</li>
<li>that Organization will make all Org Users aware of these Terms’ provisions, as applicable to such Org Users, and will cause each Org User to comply with such provisions;</li>
<li>that Organization will be solely responsible and liable for all acts and omissions of the Org Users, and any act or omission by any Org User that would constitute a breach of these Terms had it been taken by that Organization will be deemed a breach of these Terms by that Organization. Without limiting the generality of the foregoing, if an individual opens a User Account using an email address associated with or provisioned by an Organization, or if an Organization pays fees due in connection with such individual’s access to or use of the Service (or reimburses such individual for payment of such fees), then we may, in our sole discretion, deem such individual to be accessing and using the Service on behalf of that Organization.</li>
</ol>
<h1>(c) Connecting Via Third-Party Services.</h1>
<p>By connecting to the Service via a third-party service, you give us permission to access and use your information from that service, as permitted by that service, and to store your log-in credentials and/or access tokens for that service.</p>
<h1>(d) Account Security.</h1>
<h2>You may never use another User’s User Account without such User’s permission. When creating your User Account, you must provide accurate and complete information, and you must keep this information up to date. You are solely responsible for the activity that occurs on your User Account, you will keep your User Account password(s) and/or any other authentication credentials secure, and you will not share your password(s) and/or any other authentication credentials with anyone else. We encourage you to use “strong” passwords (passwords that use a combination of upper- and lower-case letters, numbers, and symbols) to</h2>
<h1>1. User Account</h1>
<p>Protect your User Account. Any Org User with administrator-level access to your User Account can modify your User Account settings, access, and billing information. We will not be liable for, and expressly disclaim liability for, any losses caused by any unauthorized use of your User Account and/or any changes to your User Account, including, without limitation, changes made by any Org User with administrator-level access to your User Account. You will notify us immediately of any breach of security or unauthorized use of your User Account.</p>
<h1>(e) Account Settings</h1>
<p>You may control certain aspects of your User Account and any associated User profile, and of the way you interact with the Service, by changing the settings in your settings page. By providing us with your email address, you consent to our using that email address to send you Service-related notices, including any notices required by Applicable Law, in lieu of communication by postal mail. We may also use that email address to send you other messages, including, without limitation, marketing and advertising messages, such as messages notifying you of changes to features of the Service and special offers (collectively, “Marketing Emails”). If you do not want to receive Marketing Emails, you may opt out of receiving them or change your preferences by contacting the Service support team at notice@runllama.ai or by clicking on the “unsubscribe” link within a Marketing Email. Opting out will not prevent you from receiving Service-related notices.</p>
<h1>1.3. Changes, Suspension, and Termination</h1>
<p>You may de-activate your User Account at any time. We may, with or without prior notice, change the Service, stop providing the Service or features of the Service to you or to Users generally, or create usage limits for the Service. We may, with or without prior notice, permanently terminate or temporarily suspend your access to your User Account and/or the Service without liability, with or without cause, and for any or no reason, including if, in our sole determination, you violate any provision of these Terms. Upon their termination for any reason or no reason, you continue to be bound by these Terms.</p>
<h1>1.4. Third-Party Products</h1>
<p>We may, from time to time, make available certain third-party products and services, including but not limited to open-source software (“Third-Party Products”) for use in connection with the Services. Such Third-Party Products may be made available under separate or additional terms and conditions, including but not limited to open source licenses, which we will make available to you as necessary.</p>
<h1>2. Access to the Service; Service Restrictions</h1>
<h1>2.1. Access to the Service</h1>
<p>Subject to your compliance with these Terms and any documentation we may make available to you, you are hereby granted a non-exclusive, limited, non-transferable, and freely revocable license to access and use the Service, solely for your personal use or internal business purposes, as applicable, strictly as permitted by the features of the Service. We may terminate the license granted in this Section at any time, for any reason or no reason. We reserve all rights not expressly granted herein in and to the Service. Notwithstanding anything to the contrary herein, certain portions of the Service may be available only during the Subscription Term(s) (as defined below), as further described in Section 7.4 (Subscription Plans).</p>
<h1>2.2. Restrictions and Acceptable Use</h1>
<p>Except to the extent a restriction is prohibited by Applicable Law, you will not do, and will not assist, permit, or enable any third party to do, any of the following:</p>
<ul>
<li>(a) disassemble, reverse engineer, decode, or decompile any part of the Service;</li>
</ul>
<hr/>
<h1>(b)</h1>
<p>use any robot, spider, scraper, off-line reader, data mining tool, data gathering or extraction tool, or any other automated means to access the Service in a manner that sends more request messages to the servers running the Service than a human can reasonably produce in the same period of time by using a conventional on-line web browser (except that LlamaIndex grants the operators of public search engines revocable permission to use spiders to copy publicly available materials from the Service for the sole purpose of, and solely to the extent necessary for, creating publicly available searchable indices of, but not caches or archives of, such materials);</p>
<h1>(c)</h1>
<p>use any content available on or via the Service (including any caption information, keywords, or other metadata) for any machine learning and/or artificial intelligence training or development purposes, or for any technologies designed or intended for the identification of natural persons;</p>
<h1>(d)</h1>
<p>copy, rent, lease, sell, loan, transfer, assign, sublicense, resell, distribute, modify, alter, or create derivative works of any part of the Service or any of our Intellectual Property (as defined below), including, without limitation by any automated or non-automated “scraping”;</p>
<h1>(e)</h1>
<p>use the Service in any manner that impacts (i) the stability of the servers running the Service, (ii) the operation or performance of the Service or any User’s use of the Service, or (iii) the behavior of other applications that use the Service;</p>
<h1>(f)</h1>
<p>take any action that imposes, or may impose (as determined by us, in our sole discretion), an unreasonable or disproportionately large load on our infrastructure;</p>
<h1>(g)</h1>
<p>use the Service in any manner or for any purpose that (i) violates, or promotes the violation of, any Applicable Law, contractual obligation, or right of any person, including, but not limited to, Intellectual Property Rights (as defined below), privacy rights, and/or rights of personality, (ii) is fraudulent, false, deceptive, or defamatory, (iii) promotes hatred, violence, or harm against any individual or group, or (iv) otherwise may be harmful or objectionable (in our sole discretion) to us or to our providers, our suppliers, Users, or any other third party;</p>
<h1>(h)</h1>
<p>use or display the Service in competition with us, to develop competing products or services, for benchmarking or competitive analysis of the Service, or otherwise to our detriment or disadvantage;</p>
<h1>(i)</h1>
<p>access any content available on or via the Service through any technology or means other than those provided by the Service or authorized by us;</p>
<h1>(j)</h1>
<p>bypass the measures we may use to prevent or restrict access to the Service, including, without limitation, features that prevent or restrict use or copying of any content or that enforce limitations on use of the Service or any portion thereof;</p>
<h1>(k)</h1>
<p>attempt to interfere with, compromise the system integrity or security of, or decipher any transmissions to or from, the servers running the Service;</p>
<h1>(l)</h1>
<p>use the Service to transmit spam, chain letters, or other unsolicited email;</p>
<h1>(m)</h1>
<h2>use the Service for any commercial solicitation purposes;</h2>
<h1>3. User Content</h1>
<h1>3.1. General.</h1>
<p>The Service may allow Users to submit, post, display, provide, share, or otherwise make available on or via the Service content such as profile information, videos, images, music, comments, questions, and other content, data, and/or information (collectively, excluding Usage Data and Feedback (as each of those terms is defined below), “User Content”). If you are an Org User, then we may, in our sole discretion, assume that all of your User Content belongs to the applicable Organization.</p>
<h1>3.2. Rights to User Content.</h1>
<p>We claim no ownership rights over User Content, and, as between you and us, all User Content that is submitted, posted, displayed, provided, shared, or otherwise made available on or via the Service by you is and will remain yours. We have the right (but not the obligation) to remove any User Content, in our sole discretion. By submitting, posting, displaying, providing, sharing, or otherwise making available any User Content on or through the Service, you hereby expressly grant, and you represent and warrant that you have all rights necessary to grant, to LlamaIndex a fully paid, royalty-free, transferable, perpetual, irrevocable, non-exclusive, and worldwide license, with the right to grant and authorize sublicenses, to use, copy, reproduce, store, modify, publish, list information regarding, edit, translate, distribute, and syndicate such User Content in whole or in part, as reasonably necessary to provide and maintain the Service and to perform such other actions as described in our Privacy Notice or as authorized by you in connection with your use of the Service. We do not train any models on User Content. LlamaIndex will encrypt the User Content both in transit and at rest. Further, LlamaIndex will only retain such User Content and other data provided by you in S3 for up to 48 hours after processing.</p>
<h1>3.3. User Content Representations and Warranties.</h1>
<p>In connection with your User Content, you affirm, represent, and warrant the following:</p>
<ul>
<li>(a) you have the written consent of each and every identifiable natural person referred to or mentioned in the User Content, if any, to use such person’s name, voice, and likeness in the manner contemplated by the Service and these Terms, and each such person has released you from any liability that may arise in relation to such use;</li>
<li>(b) you have obtained, and are solely responsible for obtaining, all consents required by Applicable Law to post User Content relating to third parties;</li>
</ul>
<hr/>
<p>(c) your User Content and our use thereof as contemplated by these Terms and the Service will not violate any Applicable Law or infringe any rights of any third party, including, but not limited to, any Intellectual Property Rights and privacy rights;</p>
<p>(d) your User Content does not include any information or material that a governmental body deems to be sensitive or classified information, and your provision of User Content in connection with the Service is not violative of any confidentiality rights of any third party;</p>
<p>(e) we may exercise the rights to your User Content granted to us under these Terms without liability for payment of any guild or other fees, residuals, payments, or royalties payable under any collective bargaining agreement or otherwise;</p>
<p>(f) your User Content does not include nudity or other sexually suggestive content; hate speech, threats, or direct attacks on an individual or group; content that is abusive, harassing, tortious, defamatory, vulgar, obscene, libelous, or invasive of another’s privacy; sexist or racially, ethnically, or otherwise discriminatory content; content that contains self-harm or excessive violence; fake or impostor profiles; illegal content or content in furtherance of harmful or illegal activities; malicious programs or code; any person’s personal information without such person’s consent; spam, machine-generated content, or unsolicited messages; and/or otherwise objectionable content; and</p>
<p>(g) to the best of your knowledge, all User Content and other information that you provide to us is truthful and accurate.</p>
<h1>3.4. Disclaimer.</h1>
<p>WE TAKE NO RESPONSIBILITY AND ASSUME NO LIABILITY FOR ANY USER CONTENT. YOU WILL BE SOLELY RESPONSIBLE FOR YOUR USER CONTENT AND THE CONSEQUENCES OF SUBMITTING, POSTING, DISPLAYING, PROVIDING, SHARING, OR OTHERWISE MAKING IT AVAILABLE ON OR THROUGH THE SERVICE, AND YOU UNDERSTAND AND ACKNOWLEDGE THAT WE ARE ACTING ONLY AS A PASSIVE CONDUIT FOR YOUR ONLINE DISTRIBUTION AND PUBLICATION OF YOUR USER CONTENT. YOU UNDERSTAND AND ACKNOWLEDGE THAT THE SERVICE MAY EXPOSE YOU TO CONTENT THAT IS INACCURATE, OBJECTIONABLE, INAPPROPRIATE FOR CHILDREN, OR OTHERWISE UNSUITED TO YOUR PURPOSE, AND YOU UNDERSTAND AND ACKNOWLEDGE THAT WE WILL NOT BE LIABLE FOR ANY DAMAGES YOU ALLEGE TO INCUR AS A RESULT OF OR RELATING TO ANY CONTENT ACCESSED ON OR THROUGH THE SERVICE.</p>
<h1>4. Our Intellectual Property</h1>
<h1>4.1. Intellectual Property Rights Definition.</h1>
<p>For the purposes of these Terms, “Intellectual Property Rights” means all patent rights, copyright rights, mask work rights, moral rights, rights of personality, trademark, trade dress and service mark rights, goodwill, trade secret rights, and any and all other intellectual property rights and proprietary rights as may now exist or hereafter come into existence, and all applications therefor and registrations, renewals, and extensions thereof, under Applicable Law.</p>
<h1>4.2. LlamaIndex Intellectual Property.</h1>
<h2>You understand and acknowledge that we (or our licensors (including other Users), as applicable) own and will continue to own all rights (including Intellectual Property Rights), title, and interest in and to the Service, all materials and content.</h2>
<p>displayed or otherwise made available on and/or through the Service (including, without limitation, images, text, graphics, illustrations, logos, photographs, audio, videos, music, and User Content belonging to other Users; but, excluding your User Content), and all software, algorithms, code, technology, and intellectual property underlying and/or included in or with the Service (collectively and individually, “Intellectual Property”). Except as explicitly provided herein, nothing in these Terms will be deemed to create a license in or under any such Intellectual Property Rights, and you will not access, sell, license, rent, modify, distribute, copy, reproduce, transmit, display, perform, publish, adapt, edit, or create derivative works of any Intellectual Property. Use of any Intellectual Property for any purpose not expressly permitted by these Terms is strictly prohibited.</p>
<h1>4.3. Usage Data.</h1>
<p>We may collect diagnostic, technical, usage, and/or related information, including information about your computers, mobile devices, systems, and software (collectively, “Usage Data”). All Usage Data is and will be owned solely and exclusively by us, and, to the extent any ownership rights in or to the Usage Data vest in you, you hereby assign to us all rights (including Intellectual Property Rights), title, and interest in and to same. Accordingly, we may use, maintain, and/or process the Usage Data or any portion thereof for any lawful purpose, including, without limitation: (a) to provide and maintain the Service; (b) to improve our products and services (including the Service), and to develop new products, services, and/or features; (c) to monitor your usage of the Service; (d) for research and analytics, including, without limitation, data analysis, identifying usage trends, and/or customer research; and (e) to share analytics and other derived Usage Data with third parties, solely in de-identified or aggregated form. The Service may contain technological measures designed to prevent unauthorized or illegal use of the Service; you understand and acknowledge that we may use these and other lawful measures to verify your compliance with these Terms and to enforce our rights, including Intellectual Property Rights, in and to the Service.</p>
<h1>4.4. Feedback.</h1>
<p>To the extent you provide us any suggestions, recommendations, or other feedback relating to the Service or to any other LlamaIndex products or services (collectively, “Feedback”), you hereby assign to us all rights (including Intellectual Property Rights), title, and interest in and to the Feedback. Accordingly, we are free to use the Feedback and any ideas, know-how, concepts, techniques, and/or other intellectual property contained in the Feedback, without providing any attribution or compensation to you or to any third party, for any purpose whatsoever, although we are not required to use any Feedback. Feedback is deemed our Confidential Information (as defined below). You acknowledge that, by acceptance of your submission of Feedback, we do not waive any rights to use similar or related ideas previously known to us, or developed by our employees, or obtained from sources other than you.</p>
<h1>5. Confidential Information</h1>
<h2>The Service may include non-public, proprietary, or confidential information of LlamaIndex (“Confidential Information”). Confidential Information includes any information that should reasonably be understood to be confidential given the nature of the information and the circumstances of disclosure, including non-public business, product, technology, and marketing information. You will: (a) protect and safeguard the confidentiality of all Confidential Information with at least the same degree of care as you would use protect your own highly sensitive confidential information, but in no event with less than a reasonable degree of care; (b) not use any Confidential Information for any purpose other than to exercise your rights, or to perform your obligations, under these Terms; and (c) not disclose any Confidential Information to any person or entity, except your service providers or financial or legal advisors who/that (i) need to</h2>
<h1>6. Payments, Billing, and Subscription Plans</h1>
<h1>6.1. Billing Policies; Taxes</h1>
<p>While certain aspects of the Services may be provided for free until use of the Services exceeds the threshold set forth via your User Account (“Threshold”), certain other aspects of the Services and/or products available via the Services may be provided for a fee or other charge (“Fee”). By exceeding the Threshold and thus electing to use non-free aspects of the Service, you agree to the pricing and payment terms applicable to you and available through your User Account (as we may update them from time to time, the “Pricing and Payment Terms”). The Pricing and Payment Terms are hereby incorporated by reference herein. We may add new products and/or services for additional Fees, add or amend Fees for existing products and/or services, and/or discontinue offering any Subscriptions at any time, in our sole discretion; provided, however, that if we have agreed to a specific Subscription Term and a corresponding Subscription Fee, then that Subscription will remain in force for that Subscription Fee during that Subscription Term. Any change to the Pricing and Payment Terms will become effective in the billing cycle following our provision of notice of such change. Except as may be expressly stated in these Terms or in the Pricing and Payment Terms, all Fees must be paid in advance, payment obligations are non-cancelable once incurred (subject to any cancellation rights set forth in these Terms), and Fees paid are non-refundable. Fees are stated exclusive of any taxes, levies, duties, or similar governmental assessments of any nature, including, for example, value-added, sales, use, and withholding taxes, assessable by any jurisdiction (collectively, but, for clarity, excluding taxes based on our net income, “Taxes”). You will be responsible for paying all Taxes associated with your purchases and/or Subscriptions in connection with the Service.</p>
<h1>6.2. Definitions</h1>
<p>(a) “Subscription” means a particular portion of the Service that is available on an automatically renewing subscription basis, and your access thereto, as applicable. For clarity, this refers to LlamaIndex’s premium subscription which charges for use of the Service beyond the Threshold.</p>
<p>(b) “Subscription Fee” means the recurring amount due as consideration for a Subscription; a Subscription Fee is one type of Fee. For clarity, the Subscription Fee will include charges incurred, in connection with the Pricing and Payment Terms, for exceeding the Threshold.</p>
<p>(c) “Third-Party Fees” means the portion of the Fee (including any Subscription Fee) retained by one (1) or more third parties, including Payment Processor, that we may engage from time to time, in our sole discretion.</p>
<p>(d) “Payment Processor” means the third-party payment processor, currently Stripe, Inc., which we engage to process payments Users make in connection with the Service.</p>
<h1>6.3. Your Payment Method</h1>
<h2>(a) General. To use non-free aspects of the Service, you must provide us with at least one (1) current, valid payment card that is accepted by us and Payment Processor (each</h2>
<p>such card, a “Payment Method”). By providing a Payment Method, you authorize each of LlamaIndex and Payment Processor to charge that Payment Method the applicable Fees and Taxes, including, if applicable, on a recurring basis until you cancel your Subscription (including any notice period specified in Section 7.4(c) (Cancellation; Refunds)). Fees and Taxes will be charged to your Payment Method on the specific payment date indicated in your User Account. In some cases, your payment date may change, for example, if your Payment Method has not successfully settled, if you changed your Subscription plan, or if your Subscription began on a date not contained in a subsequent month. The length of your billing cycle will depend on the type of Subscription in which you are enrolled, if applicable. Fees are fully earned upon payment. We may authorize your Payment Method in anticipation of Service-related charges through various methods, including authorizing it up to one (1) month of service as soon as you register for the Service.</p>
<p>(b) Third-Party Payment Processor. We or Payment Processor will attempt to verify your Payment Method(s), and may do so by processing an authorization hold, which is standard practice. To the extent Payment Processor processes payments made by you, you will be subject to terms and conditions governing the use of Payment Processor’s service. Please review such terms and conditions as well as Payment Processor’s privacy notice (each of which is available on Payment Processor’s website). You acknowledge and understand that Payment Processor may collect and retain Third-Party Fees whenever you pay Fees (including Subscription Fees). Payment must be received by Payment Processor before our acceptance of an order. We do not view or store your full credit card or other Payment Method information. For all payments, Payment Processor will collect your Payment Method details and charge your chosen Payment Method in connection with an order. If any of your account, order, or Payment Method information changes, you will promptly update such information, so that we or Payment Processor may complete your transaction(s) and/or contact you, as needed.</p>
<p>(c) Payment Representations and Warranties. You represent and warrant that: (i) the account, order, and Payment Method information you supply to us and/or to Payment Processor, as applicable, is true, accurate, correct, and complete; (ii) you are duly authorized to use the Payment Method(s); (iii) you will pay any and all charges incurred by users of your Payment Method in connection with the Service, including any applicable Fees (at the prices in effect when such charges are incurred) and Taxes; (iv) charges incurred by you will be honored by your Payment Method company; (v) you will not allow or enable anyone else to use your Subscription (including, without limitation, by sharing your password(s) or any other authentication credentials with anyone else, or by attempting to transfer your Subscription to anyone else); and (vi) you will report to us any unauthorized or prohibited access to or use of your Subscription and/or password(s) or other authentication credentials.</p>
<p>(d) Disclaimer. WE DISCLAIM ANY AND ALL LIABILITY WITH RESPECT TO, AND YOU UNDERSTAND AND ACKNOWLEDGE THAT WE ARE NOT RESPONSIBLE FOR: (I) ANY SECURITY OR PRIVACY BREACHES RELATED TO YOUR CREDIT CARD OR OTHER PAYMENT METHOD, (II) ANY FEES THAT MAY BE CHARGED TO YOU BY YOUR BANK IN CONNECTION WITH THE COLLECTION OF FEES, AND/OR (III) ANY UNAUTHORIZED USE OF YOUR CREDIT CARD, DEBIT CARD, OR OTHER PAYMENT METHOD BY A THIRD PARTY.</p>
<h1>6.4. Subscription Plans</h1>
<hr/>
<h1>Automatic Renewals</h1>
<p>Subscriptions are available on an automatically renewing subscription basis and entail payment of Subscription Fees. YOUR SUBSCRIPTION WILL BE AUTOMATICALLY CHARGED ON A WEEKLY BASIS, BASED ON THE PAYMENT AND PRICING TERMS, TO THE EXTENT YOU EXCEED THE THRESHOLD (EACH SUCH WEEK, A “SUBSCRIPTION TERM”) UNLESS AND UNTIL YOU CANCEL SUBSCRIPTION IN ACCORDANCE WITH THE CANCELLATION PROCEDURES IDENTIFIED IN SECTION 7.4(C) (CANCELLATION; REFUNDS).</p>
<h1>Automatic Billing and Policies</h1>
<p>When you enroll in a Subscription, you expressly acknowledge and agree that: (i) each of LlamaIndex and Payment Processor is authorized to charge you, at the beginning of each Subscription Term, the Subscription Fee for the applicable Subscription, any applicable Taxes, and any other charges you may incur in connection with such Subscription, subject to adjustment in accordance with these Terms; and (ii) your Subscription is continuous until the earlier of: (A) your cancellation of such Subscription (including any notice period specified in Section 7.4(c) (Cancellation; Refunds)) and (B) the suspension, discontinuation, or termination of your access to such Subscription or to the Service in accordance with these Terms. You understand and acknowledge that the amounts billed may vary due to changes to the Subscription Fee in accordance with the Pricing and Payment Terms, and/or changes in applicable Taxes, and you authorize each of LlamaIndex and Payment Processor to charge your Payment Method the changed amounts.</p>
<h1>Cancellation; Refunds</h1>
<p>You may de-activate your User Account or any Subscription at any time, in your sole discretion, by contacting us at cancel@runllama.ai and we may, subject to Section 7.1 (Billing Policies; Taxes), suspend or terminate your Subscription, your User Account, or the Service at any time, in our sole discretion. HOWEVER, YOU UNDERSTAND AND ACKNOWLEDGE THAT, UNLESS REQUIRED BY APPLICABLE LAW, (I) YOU WILL CONTINUE TO BE AUTOMATICALLY CHARGED FOR USE OF THE SERVICES WHICH EXCEEDS THE THRESHOLD AND YOU AUTHORIZE EACH OF LLAMAINDEX AND PAYMENT PROCESSOR (WITHOUT NOTICE TO YOU, UNLESS REQUIRED BY APPLICABLE LAW) TO CHARGE YOU THE APPLICABLE SUBSCRIPTION FEE AND ANY APPLICABLE TAXES, AND (II) YOU WILL NOT BE ENTITLED TO RECEIVE ANY REFUND OR CREDIT FOR ANY SUCH CANCELLATION, SUSPENSION, OR TERMINATION, NOR FOR ANY UNUSED TIME ON YOUR SUBSCRIPTION, ANY PRE-PAYMENTS MADE IN CONNECTION WITH YOUR SUBSCRIPTION, ANY LICENSE OR SUBSCRIPTION FEES FOR ANY PORTION OF THE SERVICE, ANY CONTENT OR DATA ASSOCIATED WITH YOUR USER ACCOUNT, OR ANYTHING ELSE, AND THAT ANY SUCH REFUNDS OR CREDITS MAY BE GRANTED AT OUR SOLE OPTION AND IN OUR SOLE DISCRETION. If you believe you have been improperly charged and would like to request a refund, please contact us at cancel@runllama.ai.</p>
<h1>Privacy; Data Security</h1>
<h1>Privacy</h1>
<p>We care about your privacy. By using the Service, you acknowledge that we may collect, use, and disclose your personal information and aggregated and/or anonymized data as set forth in our Privacy Notice, and that your personal information may be transferred to, and/or processed in, the United States. LlamaIndex does not train its models or products on your personal information or any User Content.</p>
<h1>Security</h1>
<h2>We care about the integrity and security of your personal information. However, we cannot guarantee that unauthorized third parties will never be able to defeat our security.</h2>
<h1>8. Your Use of Third-Party Services</h1>
<p>THE SERVICE MAY CONTAIN LINKS TO THIRD-PARTY SITES, MATERIALS, AND/OR SERVICES (COLLECTIVELY, “THIRD-PARTY SERVICES”) THAT ARE NOT OWNED OR CONTROLLED BY US, AND CERTAIN FUNCTIONALITIES OF THE SERVICE MAY REQUIRE YOUR USE OF THIRD-PARTY SERVICES. IF YOU USE A THIRD-PARTY SERVICE IN CONNECTION WITH THE SERVICE, YOU ARE SUBJECT TO AND AGREE TO, AND MUST COMPLY WITH, THE THIRD PARTY’S TERMS AND CONDITIONS MADE AVAILABLE VIA, OR AGREED IN CONNECTION WITH, ITS SERVICES. WE DO NOT ENDORSE OR ASSUME ANY RESPONSIBILITY FOR ANY THIRD-PARTY SERVICES. IF YOU ACCESS A THIRD-PARTY SERVICE FROM THE SERVICE OR SHARE YOUR USER CONTENT ON OR THROUGH ANY THIRD-PARTY SERVICE, YOU DO SO AT YOUR OWN RISK, AND YOU UNDERSTAND THAT THESE TERMS AND OUR PRIVACY NOTICE DO NOT APPLY TO YOUR USE OF ANY THIRD-PARTY SERVICE. YOU EXPRESSLY RELIEVE US FROM ANY AND ALL LIABILITY ARISING FROM YOUR ACCESS TO AND/OR USE OF ANY THIRD-PARTY SERVICE. ADDITIONALLY, YOUR DEALINGS WITH, OR PARTICIPATION IN PROMOTIONS OF, ADVERTISERS FOUND ON THE SERVICE, INCLUDING AS RELATES TO PAYMENT AND DELIVERY OF GOODS, AND ANY OTHER TERMS (SUCH AS WARRANTIES) ARE SOLELY BETWEEN YOU AND SUCH ADVERTISERS. YOU UNDERSTAND AND ACKNOWLEDGE THAT WE WILL NOT BE RESPONSIBLE FOR ANY LOSS OR DAMAGE OF ANY SORT RELATING TO YOUR DEALINGS WITH SUCH ADVERTISERS.</p>
<h1>9. Release</h1>
<p>You hereby release us from all claims, damages (whether direct, indirect, incidental, consequential, or otherwise), obligations, losses, liabilities, costs, debts, and expenses, in each case of every kind and nature, known and unknown, arising out of a dispute between you and a third party (including any other User) in connection with the Service. In addition, you waive any Applicable Law that says, in substance: “A GENERAL RELEASE DOES NOT EXTEND TO CLAIMS WHICH THE RELEASING PARTY DOES NOT KNOW OR SUSPECT TO EXIST IN HIS OR HER FAVOR AT THE TIME OF EXECUTING THE RELEASE, WHICH, IF KNOWN BY HIM OR HER, WOULD HAVE MATERIALLY AFFECTED HIS OR HER SETTLEMENT WITH THE RELEASED PARTY.”</p>
<h1>10. Indemnity</h1>
<p>You will defend, indemnify, and hold us and our subsidiaries and affiliates, and our and their respective agents, suppliers, licensors, employees, contractors, officers, and directors (collectively, including LlamaIndex, the “LlamaIndex Indemnitees”) harmless from and against any and all claims, damages (whether direct, indirect, incidental, consequential, or otherwise), obligations, losses, liabilities, costs, debts, and expenses (including, but not limited to, legal fees) arising from: (a) your access to and/or use of the Service; (b) your violation of any term of these Terms, including, without limitation, your breach of any of your representations and warranties set forth in these Terms; (c) your violation of any third-party right, including, without limitation, any privacy right or Intellectual Property Right; (d) your violation of any Applicable Law; (e) User Content or any content that is submitted via your User Account, including, without limitation, any misleading, false, or inaccurate information; (f) your willful misconduct; or (g) any third party’s access to and/or use of the Service with your username(s), password(s), or other authentication credential(s).</p>
<h1>11. No Warranty; Disclaimers</h1>
<h2>4126-4096-3663.7</h2>
<p>THE SERVICE IS PROVIDED ON AN “AS IS” AND “AS AVAILABLE” BASIS. YOUR USE OF THE SERVICE IS AT YOUR OWN RISK. TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, THE SERVICE, THE INTELLECTUAL PROPERTY, AND ANY OTHER INFORMATION AVAILABLE ON OR THROUGH THE SERVICE ARE PROVIDED WITHOUT WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND/OR NON-INFRINGEMENT. NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED BY YOU FROM US OR THROUGH THE SERVICE WILL CREATE ANY WARRANTY NOT EXPRESSLY STATED HEREIN.</p>
<p>WITHOUT LIMITING THE GENERALITY OF THE FOREGOING, INDEMNITEES WARRANTS THAT ANY CONTENT OR ANY OTHER INFORMATION CONTAINED IN, OR AVAILABLE VIA, THE SERVICE IS ACCURATE, COMPREHENSIVE, RELIABLE, USEFUL, OR CORRECT; THAT THE SERVICE WILL MEET YOUR REQUIREMENTS; THAT THE SERVICE WILL BE AVAILABLE AT ANY PARTICULAR TIME OR LOCATION, UNINTERRUPTED, OR SECURE; THAT ANY DEFECTS OR ERRORS IN THE SERVICE WILL BE CORRECTED; OR THAT THE SERVICE IS FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS. ANY CONTENT DOWNLOADED OR OTHERWISE OBTAINED THROUGH THE USE OF THE SERVICE IS SO OBTAINED AT YOUR OWN RISK, AND YOU WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGE TO YOUR COMPUTER SYSTEM(S) OR MOBILE DEVICE(S) AND/OR FOR LOSS OF DATA THAT RESULTS FROM SAME OR FROM YOUR ACCESS TO AND/OR USE OF THE SERVICE. YOU MAY HAVE OTHER STATUTORY RIGHTS, BUT THE DURATION OF STATUTORILY REQUIRED WARRANTIES, IF ANY, WILL BE LIMITED TO THE SHORTEST PERIOD PERMITTED BY APPLICABLE LAW.</p>
<p>FURTHER, LLAMAINDEX DOES NOT WARRANT, ENDORSE, GUARANTEE, RECOMMEND, OR ASSUME RESPONSIBILITY FOR ANY PRODUCT OR SERVICE ADVERTISED OR OFFERED BY ANY THIRD PARTY THROUGH THE SERVICE OR ANY HYPERLINKED WEBSITE OR SERVICE, AND LLAMAINDEX WILL NOT BE A PARTY TO, OR IN ANY WAY MONITOR, ANY TRANSACTION BETWEEN YOU AND THIRD-PARTY PROVIDERS OF PRODUCTS OR SERVICES.</p>
<p>UNITED STATES FEDERAL LAW AND SOME STATES, PROVINCES, AND OTHER JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF AND/OR LIMITATIONS ON CERTAIN IMPLIED WARRANTIES, SO THE ABOVE EXCLUSIONS AND/OR LIMITATIONS MAY NOT APPLY TO YOU. THESE TERMS GIVE YOU SPECIFIC LEGAL RIGHTS, AND YOU MAY ALSO HAVE OTHER RIGHTS, WHICH VARY FROM JURISDICTION TO JURISDICTION. THE DISCLAIMERS, EXCLUSIONS, AND LIMITATIONS UNDER THESE TERMS WILL NOT APPLY TO THE EXTENT PROHIBITED BY APPLICABLE LAW.</p>
<h1>12. Limitation of Liability</h1>
<p>TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT WILL ANY LLAMAINDEX INDEMNITEE BE LIABLE FOR ANY INDIRECT, PUNITIVE, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR EXEMPLARY DAMAGES, INCLUDING, WITHOUT LIMITATION, DAMAGES FOR LOSS OF PROFITS, GOODWILL, USE, OR DATA, OR OTHER INTANGIBLE LOSSES, ARISING OUT OF OR RELATING TO THE USE OF, OR INABILITY TO USE, THE SERVICE OR ANY PORTION THEREOF. UNDER NO CIRCUMSTANCES WILL WE BE RESPONSIBLE FOR ANY DAMAGE, LOSS, OR INJURY RESULTING FROM HACKING, TAMPERING, OR OTHER UNAUTHORIZED ACCESS TO OR USE OF THE SERVICE OR YOUR USER ACCOUNT OR THE INFORMATION CONTAINED THEREIN.</p>
<h2>TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, WE ASSUME NO LIABILITY OR RESPONSIBILITY FOR ANY (A) ERRORS, MISTAKES, OR INACCURACIES OF CONTENT;</h2>
<p>(B) PERSONAL INJURY OR PROPERTY DAMAGE, OF ANY NATURE WHATSOEVER, RESULTING FROM YOUR ACCESS TO OR USE OF THE SERVICE; (C) ANY UNAUTHORIZED ACCESS TO OR USE OF THE SERVERS RUNNING THE SERVICE AND/OR ANY AND ALL PERSONAL INFORMATION STORED THEREIN; (D) ANY INTERRUPTION OR CESSATION OF TRANSMISSION TO OR FROM THE SERVICE; (E) ANY BUGS, VIRUSES, TROJAN TRANSMITTED TO OR THROUGH THE SERVICE BY ANY THIRD PARTY; (F) ANY ERRORS OR OMISSIONS IN ANY CONTENT, OR ANY LOSS OR DAMAGE INCURRED AS A RESULT OF THE USE OF ANY CONTENT POSTED, EMAILED, TRANSMITTED, THROUGH THE SERVICE; AND/OR (G) YOUR DATA, ANY USER CONTENT, OR THE DEFAMATORY, OFFENSIVE, OR ILLEGAL CONDUCT OF ANY THIRD PARTY.</p>
<p>HORSES, OR THE LIKE THAT MAY BE OR OTHERWISE MADE AVAILABLE</p>
<p>IN NO EVENT WILL ANY LLAMAINDEX INDEMNITEE BE LIABLE TO YOU FOR ANY CLAIMS, PROCEEDINGS, LIABILITIES, OBLIGATIONS, DAMAGES, LOSSES, OR COSTS IN AN AMOUNT EXCEEDING THE AMOUNT YOU PAID TO US HEREUNDER OR ONE HUNDRED U.S. DOLLARS ($100.00), WHICHEVER IS GREATER. THIS LIMITATION OF LIABILITY SECTION APPLIES WHETHER THE ALLEGED LIABILITY IS BASED ON CONTRACT, TORT, NEGLIGENCE, STRICT LIABILITY, OR ANY OTHER BASIS, EVEN IF WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.</p>
<p>SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF AND/OR LIMITATIONS ON INCIDENTAL OR CONSEQUENTIAL DAMAGES, SO THE LIMITATIONS MAY NOT APPLY TO YOU. THESE TERMS GIVE YOU SPECIFIC LEGAL RIGHTS, AND YOU MAY ALSO HAVE OTHER RIGHTS, WHICH VARY FROM JURISDICTION TO JURISDICTION. THE DISCLAIMERS, EXCLUSIONS, AND LIMITATIONS OF LIABILITY UNDER THESE TERMS WILL NOT APPLY TO THE EXTENT PROHIBITED BY APPLICABLE LAW.</p>
<h1>13. Governing Law, Arbitration, and Class Action/Jury Trial Waiver</h1>
<h1>13.1. Governing Law.</h1>
<h2>You agree that: (a) the Service will be deemed solely based in the State of Delaware; and (b) the Service will be deemed a passive one that does not give rise to personal jurisdiction over us, either specific or general, in jurisdictions other than Delaware. These Terms will be governed by the internal substantive laws of the State of Delaware, without respect to its conflict of laws principles. The parties acknowledge that these Terms evidence a transaction involving interstate commerce. Notwithstanding the preceding sentences with respect to the substantive law governing these Terms, the Federal Arbitration Act (9 U.S.C. §§ 1-16) (as it may be amended, “FAA”) governs the interpretation and enforcement of the Arbitration Agreement below and preempts all state laws (and laws of other jurisdictions) to the fullest extent permitted by Applicable Law. If the FAA is found to not apply to any issue that arises from or relates to the Arbitration Agreement, then that issue will be resolved under and governed by the law of the U.S. state where you live (if applicable) or the jurisdiction mutually agreed upon in writing by you and us. The application of the United Nations Convention on Contracts for the International Sale of Goods is expressly excluded. You agree to submit to the exclusive personal jurisdiction of the federal and state courts located in Delaware for any actions for which we retain the right to seek injunctive or other equitable relief in a court of competent jurisdiction to prevent the actual or threatened infringement, misappropriation, or violation of our data security, Confidential Information, or Intellectual Property Rights, as set forth in the Arbitration Agreement below, including any provisional relief required to prevent irreparable harm. You agree that Delaware is the proper and exclusive forum for any appeals of an arbitration award, or for trial court proceedings in the event that the Arbitration Agreement below is found to be unenforceable. These Terms were drafted in the English language and this English language version of the</h2>
<p>Terms is the original, governing instrument of the understanding between you and us. In the event of any conflict between the English version of these Terms and any translation, the English version will prevail.</p>
<h1>13.2. Arbitration Agreement</h1>
<p>(a) General. READ THIS SECTION CAREFULLY BECAUSE IT REQUIRES THE PARTIES TO ARBITRATE THEIR DISPUTES AND LIMITS THE MANNER IN WHICH YOU CAN SEEK RELIEF FROM US. This Arbitration Agreement applies to and governs any dispute, controversy, or claim between you and us that arises out of or relates to, directly or indirectly: (i) these Terms, including the formation, existence, breach, termination, enforcement, interpretation, validity, and enforceability thereof; (ii) access to or use of the Service, including receipt of any advertising or marketing communications; (iii) any transactions through, by, or using the Service; or (iv) any other aspect of your relationship or transactions with us, directly or indirectly, as a User or consumer (each, a “Claim,” and, collectively, “Claims”). This Arbitration Agreement will apply, without limitation, to all Claims that arose or were asserted before or after your consent to these Terms.</p>
<p>(b) Opting Out of Arbitration Agreement. If you are a new User, you can reject and opt out of this Arbitration Agreement within thirty (30) days of accepting these Terms by emailing us at dispute@runllama.ai with your full, legal name and stating your intent to opt out of this Arbitration Agreement. Opting out of this Arbitration Agreement does not affect the binding nature of any other part of these Terms, including the provisions regarding controlling law or the courts in which any disputes must be brought.</p>
<h2>(c) Dispute-Resolution Process. For any Claim, you will first contact us at dispute@runllama.ai and attempt to resolve the Claim with us informally. In the unlikely event that we have not been able to resolve a Claim after sixty (60) days, we each agree to resolve such Claim exclusively through binding arbitration by JAMS before a single arbitrator (the “Arbitrator”), under the Optional Expedited Arbitration Procedures then in effect for JAMS (the “Rules”), except as provided herein. JAMS may be contacted at www.jamsadr.com, where the Rules are available. In the event of any conflict between the Rules and this Arbitration Agreement, this Arbitration Agreement will control. The arbitration will be conducted in the U.S. county where you live (if applicable) or Sussex County, Delaware, unless you and LlamaIndex agree otherwise. If you are using the Service for commercial purposes, each party will be responsible for paying any JAMS filing and administrative fees and Arbitrator fees in accordance with the Rules, and the award rendered by the Arbitrator will include costs of arbitration, reasonable attorneys’ fees, and reasonable costs for expert and other witnesses. If you are an individual using the Service for non-commercial purposes: (i) JAMS may require you to pay a fee for the initiation of your case, unless you apply for and successfully obtain a fee waiver from JAMS; (ii) the award rendered by the Arbitrator may include your costs of arbitration, your reasonable attorneys’ fees, and your reasonable costs for expert and other witnesses; and (iii) you may sue in a small claims court of competent jurisdiction without first engaging in arbitration, but this would not absolve you of your commitment to engage in the informal dispute resolution process. Any judgment on the award rendered by the Arbitrator may be entered in any court of competent jurisdiction. You and we agree that the Arbitrator, and not any federal, state, or local court or agency, will have exclusive authority to resolve any disputes relating to the scope, interpretation, applicability, enforceability, or formation of this Arbitration Agreement, including any claim that all or any part of this Arbitration Agreement is void or voidable. The Arbitrator will also be responsible for determining all threshold</h2>
<p>arbitrability issues, including issues relating to whether these Terms are, or whether any provision of these Terms is, unconscionable or illusory, and any defense to arbitration, including waiver, delay, laches, unconscionability, and/or estoppel.</p>
<p>(d) Equitable Relief. NOTHING IN THIS ARBITRATION AGREEMENT WILL BE DEEMED AS: PREVENTING US FROM SEEKING INJUNCTIVE OR OTHER EQUITABLE RELIEF FROM THE COURTS AS NECESSARY TO PREVENT THE ACTUAL OR THREATENED INFRINGEMENT, MISAPPROPRIATION, OR VIOLATION OF OUR DATA SECURITY, CONFIDENTIAL INFORMATION, OR INTELLECTUAL PROPERTY RIGHTS; OR PREVENTING YOU FROM ASSERTING CLAIMS IN A SMALL CLAIMS COURT, PROVIDED THAT YOUR CLAIMS QUALIFY AND SO LONG AS THE MATTER REMAINS IN SUCH COURT AND ADVANCES ON ONLY AN INDIVIDUAL (NON-CLASS, NON-COLLECTIVE, AND NON-REPRESENTATIVE) BASIS.</p>
<p>(e) Severability. If this Arbitration Agreement is found to be void, unenforceable, or unlawful, in whole or in part, the void, unenforceable, or unlawful provision, in whole or in part, will be severed. Severance of the void, unenforceable, or unlawful provision, in whole or in part, will have no impact on the remaining provisions of this Arbitration Agreement, which will remain in force, or on the parties’ ability to compel arbitration of any remaining Claims on an individual basis pursuant to this Arbitration Agreement. Notwithstanding the foregoing, if the Class Action/Jury Trial Waiver below is found to be void, unenforceable, or unlawful, in whole or in part, because it would prevent you from seeking public injunctive relief, then any dispute regarding the entitlement to such relief (and only that relief) must be severed from arbitration and may be litigated in a civil court of competent jurisdiction. All other claims for relief subject to arbitration under this Arbitration Agreement will be arbitrated under its terms, and the parties agree that litigation of any dispute regarding the entitlement to public injunctive relief will be stayed pending the outcome of any individual claims in arbitration.</p>
<h1>13.3. Class Action/Jury Trial Waiver.</h1>
<p>BY ENTERING INTO THESE TERMS, YOU AND LLAMAINDEX ARE EACH WAIVING THE RIGHT TO A TRIAL BY JURY OR TO BRING, JOIN, OR PARTICIPATE IN ANY PURPORTED CLASS ACTION, COLLECTIVE ACTION, PRIVATE ATTORNEY GENERAL ACTION, OR OTHER REPRESENTATIVE PROCEEDING OF ANY KIND AS A PLAINTIFF OR CLASS MEMBER. THE FOREGOING APPLIES TO ALL USERS (BOTH NATUAL PERSONS AND ENTITIES), REGARDLESS OF WHETHER YOU HAVE OBTAINED OR USED THE SERVICE FOR PERSONAL, COMMERCIAL, OR OTHER PURPOSES. THIS CLASS ACTION/JURY TRIAL WAIVER APPLIES TO CLASS ARBITRATION, AND, UNLESS WE AGREE OTHERWISE, THE ARBITRATOR MAY NOT CONSOLIDATE MORE THAN ONE PERSON’S OR ENTITY’S CLAIMS. YOU AND LLAMAINDEX AGREE THAT THE ARBITRATOR MAY AWARD RELIEF ONLY TO AN INDIVIDUAL CLAIMANT AND ONLY TO THE EXTENT NECESSARY TO PROVIDE RELIEF ON YOUR INDIVIDUAL CLAIM(S). ANY RELIEF AWARDED MAY NOT AFFECT OTHER USERS.</p>
<h1>14. U.S. Government Restricted Rights</h1>
<p>To the extent the Service is being used by or on behalf of the U.S. Government, the Service will be deemed commercial computer software or commercial computer software documentation (as applicable). Accordingly, if you are an agency of the U.S. Government or any contractor therefor, you receive only those rights with respect to the Service as are granted to all other Users hereunder, in accordance with 48 C.F.R. §227.7202 and 48 C.F.R. §12.212, as applicable.</p>
<h2>4126-4096-3663.7</h2>
<h1>15. Export Controls</h1>
<p>You understand and acknowledge that the Service may be subject to export control laws and regulations. You will comply with all applicable import and export and re-export control and trade and economic sanctions laws and regulations, including the Export Administration Regulations maintained by the U.S. Department of Commerce, trade and economic sanctions maintained by the U.S. Treasury Department’s Office of Foreign Assets Control (“OFAC”), and the International Traffic in Arms Regulations maintained by the U.S. State Department. You represent and warrant that you are not, and that no person to whom you make the Service available or that is acting on your behalf, or, if you are an Organization, that no person or entity owning 50% or more of your equity securities or other equivalent voting interests, is (a) listed on the List of Specially Designated Nationals and Blocked Persons or on any other list of sanctioned, prohibited, or restricted parties administered by OFAC or by any other governmental entity, or (b) located in, a national or resident of, or a segment of the government of, any country or territory for which the United States maintains trade or economic sanctions or embargoes or that has been designated by the U.S. Government as a “terrorist supporting” region.</p>
<h1>16. General Provisions</h1>
<h1>16.1. Assignment</h1>
<p>These Terms, and any rights and licenses granted hereunder, may not be transferred or assigned by you without our prior express written consent, but may be assigned by us without restriction. Any attempted transfer or assignment in violation hereof will be null and void.</p>
<h1>16.2. Notification Procedures and Changes to these Terms</h1>
<p>We may provide notifications, whether such notifications are required by Applicable Law or are for marketing or other business-related purposes, to you via email notice or written or hard copy notice, or through posting of such notice on the Site(s) as we determine, in our sole discretion. We reserve the right to determine the form and means of providing notifications to Users, provided that you may opt out of certain means of notification, as required under Applicable Law or as described in these Terms. We are not responsible for any automatic filtering you or your network provider may apply to email notifications we send to the email address you provide us. We may, in our sole discretion, modify or update these Terms from time to time, and so you should review this page periodically. When we change these Terms in a material manner, we will update the ‘last modified’ date at the top of this page and notify you that material changes have been made to these Terms. These Terms apply to and govern your access to and use of the Service effective as of the start of your access to the Service, even if such access began before publication of these Terms. Your continued use of the Service after any change to these Terms constitutes your acceptance of the new Terms of Service. If you do not agree to any part of these Terms or to any future Terms of Service, do not access or use (or continue to access or use) the Service.</p>
<h1>16.3. Entire Agreement; Severability</h1>
<h2>These Terms, together with any amendments and any additional agreements you may enter into with us in connection with the Service, will constitute the entire agreement between you and us concerning the Service. Any statements or comments made between you and any of our employees or representatives are expressly excluded from these Terms and will not apply to you or us, or to your access to or use of the Service. Except as otherwise stated in the Arbitration Agreement, if any provision of these Terms is deemed invalid by a court of competent jurisdiction, the invalidity of such provision will not affect the validity of the remaining provisions of these Terms, which will remain in full force and effect.</h2>
<h1>16.4. No Waiver</h1>
<p>No waiver of any term of these Terms will be deemed a further or continuing waiver of such term or of any other term, and our failure to assert any right or provision under these Terms will not constitute a waiver of such right or provision.</p>
<h1>16.5. California Residents</h1>
<p>The provider of the Service is set forth herein. If you are a California resident, in accordance with Cal. Civ. Code §1789.3, you may report complaints to the Complaint Assistance Unit of the Division of Consumer Services of the California Department of Consumer Affairs by contacting it in writing at 1625 North Market Blvd., Suite N 112 Sacramento, CA 95834, or by telephone at (800) 952-5210 or (916) 445-1254.</p>
<h1>16.6. Contact</h1>
<p>If you have any questions about these Terms and/or the Service, please contact us at notice@runllama.ai.</p>
    </main>
  );
} 
